apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # annotations:
      #   prometheus.io/port: '9113'
      #   prometheus.io/scrape: 'true'
      labels:
        environment: staging
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: secret-dockercfg

      containers:
      - name: landing
        image: ghcr.io/toxics-space/landing:{{ .Values.version }}
        imagePullPolicy: Always
        ports:
        - name: landing-port
          containerPort: 80
        env:
        - name: SERVER_NAME
          value: landing_staging
      
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11.0'
        args:
          - '-nginx.scrape-uri=http://localhost:8080/metrics'
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - name: monitoring
          containerPort: 9113
