apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-app
  namespace: prod
  labels:
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-app
  template:
    metadata:
      annotations:
        prometheus.io/port: '9113'
        prometheus.io/scrape: 'true'
      labels:
        environment: prod
        app: landing-app
    spec:
      imagePullSecrets:
      - name: secret-dockercfg

      containers:
      - name: landing
        image: ghcr.io/toxics-space/landing:latest
        imagePullPolicy: Always
        ports:
        - name: landing-port
          containerPort: 80
        env:
        - name: SERVER_NAME
          value: landing_staging
      
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11.0'
        args:
          - '-nginx.scrape-uri=http://localhost:8080/metrics'
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - name: monitoring
          containerPort: 9113

# kubectl get all -n staging
# kubectl rollout restart  deployment/ui-app -n staging